Parameters:
  DistributionBucketName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /account/services/artifact.bucket
    Description: SSM parameter containing the S3 bucket name holding distribution artifacts
Resources:
  TestScheduledLambdaServiceRoleB6B23AE9:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Tags:
        - Key: App
          Value: hello-world
        - Key: Stack
          Value: aws-learning
        - Key: Stage
          Value: CODE
  TestScheduledLambdaServiceRoleDefaultPolicy651537D1:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: arn:aws:s3:::MyBucktName
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":s3:::"
                    - Ref: DistributionBucketName
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":s3:::"
                    - Ref: DistributionBucketName
                    - /aws-learning/CODE/hello-world/hello-world-lambda.zip
          - Action: ssm:GetParametersByPath
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:ssm:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :parameter/CODE/aws-learning/hello-world
          - Action:
              - ssm:GetParameters
              - ssm:GetParameter
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:ssm:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :parameter/CODE/aws-learning/hello-world/*
        Version: "2012-10-17"
      PolicyName: TestScheduledLambdaServiceRoleDefaultPolicy651537D1
      Roles:
        - Ref: TestScheduledLambdaServiceRoleB6B23AE9
  TestScheduledLambda80C1CB22:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: DistributionBucketName
        S3Key: aws-learning/CODE/hello-world/hello-world-lambda.zip
      Role:
        Fn::GetAtt:
          - TestScheduledLambdaServiceRoleB6B23AE9
          - Arn
      Environment:
        Variables:
          STACK: aws-learning
          STAGE: CODE
          APP: hello-world
      Handler: main.handler
      MemorySize: 128
      Runtime: nodejs18.x
      Tags:
        - Key: App
          Value: hello-world
        - Key: Stack
          Value: aws-learning
        - Key: Stage
          Value: CODE
      Timeout: 5
    DependsOn:
      - TestScheduledLambdaServiceRoleDefaultPolicy651537D1
      - TestScheduledLambdaServiceRoleB6B23AE9
  TestScheduledLambdaTestScheduledLambdarate1minute0029959BB:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: rate(1 minute)
      State: ENABLED
      Targets:
        - Arn:
            Fn::GetAtt:
              - TestScheduledLambda80C1CB22
              - Arn
          Id: Target0
  TestScheduledLambdaTestScheduledLambdarate1minute0AllowEventRuleLambdaTemplateCODETestScheduledLambda56132882E17A7FFC:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - TestScheduledLambda80C1CB22
          - Arn
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - TestScheduledLambdaTestScheduledLambdarate1minute0029959BB
          - Arn

